# Generated by Django 5.0.2 on 2024-03-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idContrato', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('folio', models.IntegerField(unique=True)),
                ('tipo', models.CharField(choices=[('Compra', 'Compra')], default='Compra', max_length=45)),
                ('archivo', models.FileField(upload_to='archivos/contratos/')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vigente', 'Vigente'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=45)),
            ],
        ),
    ]
