# Generated by Django 5.0.2 on 2024-03-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('idPredio', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('coordenadas', models.CharField(max_length=45)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='archivos/imagenes/predios/')),
                ('fechaSiembra', models.DateField()),
                ('plantas', models.IntegerField()),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
