# Generated by Django 5.0.2 on 2024-03-14 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Predio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jima',
            fields=[
                ('idJima', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('precioKilo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pesoPromedioPlanta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Predio.predio')),
            ],
        ),
    ]
