# Generated by Django 5.0.2 on 2024-03-14 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inversor', '0002_initial'),
        ('Predio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('idOferta', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cantidadPlantas', models.IntegerField()),
                ('precioPlanta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vigente', 'Vigente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Finalizada', 'Finalizada')], max_length=45)),
                ('tipo', models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], max_length=45)),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Predio.predio')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inversor.inversor')),
            ],
        ),
    ]
