# Generated by Django 5.0.2 on 2024-03-14 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetalleVenta', '0001_initial'),
        ('Oferta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='oferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Oferta.oferta'),
        ),
    ]
